function switchTab(t,b){document.querySelectorAll('.content').forEach(e=>e.style.display='none');document.querySelectorAll('.tab').forEach(e=>e.classList.remove('active'));document.getElementById('tab-'+t).style.display='flex';b.classList.add('active');}
function setFilter(t,b){document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('#chatMessages>[data-type]').forEach(e=>{if(t==='all')e.style.display='';else if(t==='official')e.style.display=e.dataset.type==='official'?'':'none';else e.style.display=(e.dataset.type==='neighbour'||e.dataset.type==='me')?'':'none';});}
var userAddress=localStorage.getItem('sc_address')||'Moreton Bay Region';
var userPhone=localStorage.getItem('sc_phone')||'';
var userSuburb=localStorage.getItem('sc_suburb')||'';
var userDisplay=localStorage.getItem('sc_display')||'Neighbour';
function sendMsg(){var i=document.getElementById('chatInput');if(!i.value.trim())return;var content=i.value.trim();i.value='';document.getElementById('sendBtn').style.background='#ccc';fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:userPhone,address:userAddress,suburb:userSuburb,content:content,display_name:userDisplay})}).then(function(){loadMessages();}).catch(function(){});var a=document.getElementById('aiNote');a.style.display='block';setTimeout(function(){a.style.display='none';},3000);}
async function loadMessages(){try{var res=await fetch('/api/messages');var data=await res.json();var msgs=data.messages||[];var container=document.getElementById('myMessages');container.innerHTML='';msgs.forEach(function(msg){var isMe=msg.phone===userPhone;var n=new Date(msg.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});var displayName=msg.display_name||msg.address||'Neighbour';var d=document.createElement('div');d.className='msg-row'+(isMe?' me':'');d.dataset.type=isMe?'me':'neighbour';if(isMe){d.innerHTML='<div style="max-width:75%"><div class="bubble me"><p>'+msg.content+'</p></div></div><div class="msg-av">&#127968;</div>';}else{d.innerHTML='<div class="msg-av">&#127968;</div><div style="max-width:75%"><div class="msg-meta">'+displayName+' &middot; '+n+'</div><div class="bubble them"><p>'+msg.content+'</p></div></div>';}container.appendChild(d);});document.getElementById('chatBottom').scrollIntoView({behavior:'smooth'});}catch(e){console.log('msg error:',e);}}
loadMessages();
setInterval(loadMessages,10000);
function toggleLike(b,c){if(b.classList.contains('liked')){b.classList.remove('liked');b.textContent=c>1?'&#128077; '+(c-1):'&#128077;';}else{b.classList.add('liked');b.textContent='&#128077; '+(c+1);}}
var pT;function showPush(n){var b=document.getElementById('pushBanner');document.getElementById('pushIcon').textContent=n.icon;document.getElementById('pushTitle').textContent=n.title;document.getElementById('pushBodyText').textContent=n.body;b.style.background=n.color||'#2d4a2d';b.style.display='flex';clearTimeout(pT);pT=setTimeout(dismissPush,5000);}
function dismissPush(){document.getElementById('pushBanner').style.display='none';}
setTimeout(function(){showPush({icon:'&#128680;',title:'QPS Alert — Patrol Active',body:'Police patrols increased on Summerstone Estate. Stay vigilant.',color:'#c62828'});},3000);
var INCS={1:{emoji:'&#128663;',title:'Suspicious Vehicle',addr:'Near 22 Summerstone Blvd',time:'Today 9:15 AM',sev:'high',sc:'#e53935',desc:'White sedan parked outside No. 22 for 3+ hours, engine running. QPS alerted and patrols increased.',status:'Patrols active',rep:'QPS',color:'#fb8c00'},2:{emoji:'&#128230;',title:'Package Theft',addr:'14 Summerstone Blvd',time:'Yesterday 6:32 PM',sev:'medium',sc:'#fb8c00',desc:'Parcel stolen from front porch 5-7pm. Ring camera footage available. Reported to QPS.',status:'QPS notified',rep:'14 Summerstone Blvd',color:'#e53935'},3:{emoji:'&#128394;',title:'Graffiti - Freshwater St',addr:'Freshwater St corner',time:'2 days ago',sev:'low',sc:'#43a047',desc:'Graffiti on bus shelter and fence. Council notified, clean-up scheduled Thursday.',status:'Council notified',rep:'8 Summerstone Blvd',color:'#7b1fa2'},4:{emoji:'&#128690;',title:'Bike Stolen',addr:'Amber St',time:'3 days ago',sev:'medium',sc:'#fb8c00',desc:'Red Trek mountain bike stolen from unlocked side gate. Serial 4KT-2291. Police report filed.',status:'Police report filed',rep:'21 Amber St',color:'#e53935'},5:{emoji:'&#128021;',title:'Loose Aggressive Dog',addr:'Bloom Dr',time:'Today 7:45 AM',sev:'high',sc:'#e53935',desc:'Large tan staffy running loose, appeared aggressive toward a child on bike. Council rangers called.',status:'Rangers called',rep:'3 Bloom Dr',color:'#388e3c'},6:{emoji:'&#9888;',title:'Door-to-Door Scam',addr:'Summerstone Blvd',time:'Yesterday',sev:'medium',sc:'#fb8c00',desc:'Men claiming to be from energy company pressuring residents to sign contracts. NOT legitimate.',status:'Scam Aware notified',rep:'Multiple neighbours',color:'#fb8c00'}};
var selI=null;
function selectInc(id){selI=selI===id?null:id;document.querySelectorAll('[id^=incBtn]').forEach(function(b){b.classList.remove('selected');});var detail=document.getElementById('incDetail');if(!selI){detail.style.display='none';return;}document.getElementById('incBtn'+id).classList.add('selected');var inc=INCS[id];detail.style.borderLeftColor=inc.color;detail.style.display='block';detail.innerHTML='<div class="inc-detail-top"><span class="inc-emoji-lg">'+inc.emoji+'</span><div style="flex:1;"><div style="display:flex;align-items:center;margin-bottom:3px;"><div class="inc-title">'+inc.title+'</div><span class="sev-badge" style="background:'+inc.sc+';">'+inc.sev.toUpperCase()+'</span></div><div class="inc-addr-text">&#128205; '+inc.addr+' &middot; '+inc.time+'</div></div><button class="close-btn" onclick="selectInc('+id+')">&#10005;</button></div><p class="inc-desc-text">'+inc.desc+'</p><div class="tags"><span class="tag">By: '+inc.rep+'</span><span class="tag" style="background:#e8f5e9;color:#2e7d32;">&#10003; '+inc.status+'</span></div>';}
var rOn=true,rM=500;
function updateRadius(v){rM=parseInt(v);var d=rM>=1000?(rM/1000).toFixed(1)+'km':rM+'m';document.getElementById('radiusVal').textContent=d;document.getElementById('radiusLabelTxt').textContent=d;var r=(rM/1500)*100;document.getElementById('radiusRing').setAttribute('r',r);document.getElementById('radiusLabelBg').setAttribute('x',155-22);document.getElementById('radiusLabelBg').setAttribute('y',143-r-14);document.getElementById('radiusLabelTxt').setAttribute('x',155);document.getElementById('radiusLabelTxt').setAttribute('y',143-r-5);var ic=Math.max(1,Math.round(1+(rM/1500)*5));document.getElementById('radiusInfo').textContent='&#128225; '+ic+' of 6 incidents within your '+d+' range &middot; '+(6-ic)+' filtered out';}
function setRadius(v){document.getElementById('radiusSlider').value=v;updateRadius(v);}
function toggleRadius(){rOn=!rOn;var t=document.getElementById('radiusToggle');t.textContent=rOn?'ON':'OFF';t.className=rOn?'radius-toggle':'radius-toggle off';['radiusRing','radiusLabelBg','radiusLabelTxt','radiusInfo'].forEach(function(id){document.getElementById(id).style.display=rOn?'':'none';});}
function openReport(){document.getElementById('reportModal').style.display='flex';}
function closeReport(){document.getElementById('reportModal').style.display='none';document.getElementById('reportForm').style.display='block';document.getElementById('reportSuccess').style.display='none';document.getElementById('reportDesc').value='';document.querySelectorAll('.type-btn').forEach(function(b,i){b.className=i===0?'type-btn active':'type-btn';});}
function setType(b){document.querySelectorAll('.type-btn').forEach(function(x){x.className='type-btn';});b.className='type-btn active';}
async function submitReport(){var desc=document.getElementById('reportDesc').value.trim();if(!desc)return;var activeType=document.querySelector('.type-btn.active');var type=activeType?activeType.textContent.trim():'General';try{await fetch('/api/incidents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:userPhone,address:userAddress,type:type,description:desc})});}catch(e){console.log('Incident error:',e);}document.getElementById('reportForm').style.display='none';document.getElementById('reportSuccess').style.display='block';setTimeout(function(){closeReport();showPush({icon:'&#128680;',title:'Incident Reported',body:'Your report submitted. Neighbours being notified.',color:'#e65100'});},2000);}
function messageAdmin(){var msg=prompt('Send a message to Street Connect admin:');if(msg&&msg.trim()){fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:userPhone,address:userAddress,suburb:'ADMIN_MSG',content:'[ADMIN] '+msg.trim(),display_name:userDisplay})}).then(function(){alert('Message sent!');});}}
